rabbitmq:
  host: ${RABBITMQ_HOST:127.0.0.1}
  port: ${RABBITMQ_PORT:5672}
  username: ${RABBITMQ_USERNAME:admin}
  passport: ${RABBITMQ_PASSWORD:admin}
  virtualhost: ${RABBITMQ_VHOST:/}
  switchFlag: ${RABBITMQ_ENABLE:false}
  pool_size: ${RABBITMQ_POOL_SIZE:5}
